Repository openkcm/registry, pull requests merged in 2025-08, with the labels that each got.

#3 fix: update some of the base setup
  .github/dependabot.yaml
  .release-please-manifest.json
  .release/release-metadata.hcl
  README.md
  REUSE.toml
  Taskfile.yaml
Labels: bug, ci-cd

#10 chore: Improve naming, docs and startup scripts
  Makefile
  README.md
  cmd/registry/main.go
  config.yaml
  docker-compose.yaml
  local/registry/config.yaml
Labels: dev-ops

#11 chore: Run integration tests on PR
  .github/workflows/integration-test.yaml
  .gitignore
  Makefile
  build_version.json
  docker-compose.yaml
  version.go
Labels: ci-cd, dev-ops, test

#13 fix: Fix readiness probe
  cmd/registry/main.go
Labels: bug, ci-cd, dev-ops

#14 fix: fix some chart configuration and version; Adjust the status for grpc server
  charts/registry/Chart.yaml
  charts/registry/templates/deployment.yaml
  charts/registry/templates/hpa.yaml
  charts/registry/templates/pdb.yaml
  charts/registry/values.yaml
  cmd/registry/main.go
  config.yaml
  internal/config/config.go
  local/registry/config.yaml
Labels: bug, helm-chart
