Repository openkcm/registry, pull requests merged in 2025-09, with the labels that each got.

#25 feat: List systems by type
  integration/system_test.go
  internal/model/system.go
  internal/model/system_type.go
  internal/model/system_type_test.go
  internal/repository/query.go
  internal/service/system.go
Labels: tests, feature

#18 test: add helm tests
  .github/workflows/helm-test.yaml
  Dockerfile.dev
  Makefile
  helm_dependencies.sh
  helm_registry.sh
  helmtest/registry_test.go
Labels: ci-cd, dependencies, tests, dev-ops, test

#53 chore: updated Dockerfile base image
  Dockerfile
Labels: dev-ops
